[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "0xdab0f60efed6a83cb64f3b50bbd3b675fc815b691d8e01f8f2b7472d714382c6"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "testnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
